apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
    spec:
      containers:
      - name: s3-app
        image: s3-app:latest
        imagePullPolicy: Never
        env:
          - name: S3_ENDPOINT
            value: "http://minio:9000"
          - name: S3_ACCESS_KEY
            value: "minioadmin"
          - name: S3_SECRET_KEY
            value: "minioadmin"
          - name: S3_BUCKET
            value: "test-bucket"
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: s3-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: s3-app
